apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service:latest  # Replace with your image
          imagePullPolicy: Never

          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  type: LoadBalancer    # Exposes the service externally
  ports:
    - protocol: TCP
      port: 81         # Exposed port outside the cluster
      targetPort: 8080 # Port inside the container
